FROM mcr.microsoft.com/dotnet/core/sdk as build
WORKDIR /aspnet
COPY . .
RUN dotnet build
RUN dotnet publish --no-restore -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /dist
ENV ASPNETCORE_URL=http://*:5000
COPY --from=build /aspnet/out /dist 
RUN pwd
CMD [ "dotnet", "Devops.Client.dll" ]
